baseURL = 'https://alirezashiasi.com/'
languageCode = 'en-us'
title = 'Alireza Shiasi'
theme = 'anatole'

[params]
    profilePicture = "images/Alireza-Shiasi-square-ai.png"
    doNotLoadAnimations = true # Animations are loaded by default
    contentratio = 0.7
    readMore = true
    mainSections = []

    # Social links
    [[params.socialIcons]]
    icon = "fa-brands fa-linkedin"
    title = "Linkedin"
    url = "https://linkedin.com/in/alirezashiasi"

    [[params.socialIcons]]
    icon = "fa-brands fa-instagram"
    title = "instagram"
    url = "https://www.instagram.com/alirezashyasi/"

    [[params.socialIcons]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/shiasi"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true





defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/english'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 0
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Website ğŸ”—"
        identifier = "website"
        weight = 999
        url = "https://shiasi.com"
    [languages.en.params]
      title = 'Alireza Shiasi'
      author = 'Alireza Shiasi'
      description = 'Business Researcher and Developer with a Sustainability Twist | Construction Management Strategist | Enthusiast of Open-Source Technologies (Linux, BSD, etc.) | Writer and Occasional Poet'

  [languages.fa]
    contentDir = 'content/persian'
    disabled = false
    languageCode = 'fa-IR'
    languageDirection = 'rtl'
    languageName = 'Ù¾Ø§Ø±Ø³ÛŒ'
    weight = 1
    [languages.fa.menu]
      [[languages.fa.menu.main]]
        name = "ÙˆØ¨Ø³Ø§ÛŒØª ğŸ”— "
        identifier = "website"
        weight = 999
        url = "https://shiasi.com"
    [languages.fa.params]
      title = 'Ø¹Ù„ÛŒØ±Ø¶Ø§ Ø´ÛŒØ§Ø³ÛŒ'
      author = 'Ø¹Ù„ÛŒØ±Ø¶Ø§ Ø´ÛŒØ§Ø³ÛŒ'
      description = 'Ù¾Ú˜ÙˆÙ‡Ø´Ú¯Ø± Ùˆ ØªÙˆØ³Ø¹Ù‡â€ŒØ¯Ù‡Ù†Ø¯Ù‡ Ú©Ø³Ø¨â€ŒÙˆÚ©Ø§Ø± Ø¨Ø§ Ø·Ø¹Ù… Ù¾Ø§ÛŒØ¯Ø§Ø±ÛŒ | Ø§Ø³ØªØ±Ø§ØªÚ˜ÛŒØ³Øª Ù…Ø¯ÛŒØ±ÛŒØª Ø³Ø§Ø®Øª | Ø¹Ù„Ø§Ù‚Ù‡â€ŒÙ…Ù†Ø¯ Ø¨Ù‡ ÙÙ†Ø§ÙˆØ±ÛŒâ€ŒÙ‡Ø§ÛŒ Ù…ØªÙ†â€ŒØ¨Ø§Ø² (Ù„ÛŒÙ†ÙˆÚ©Ø³ØŒ Ø¨ÛŒâ€ŒØ§Ø³â€ŒØ¯ÛŒ Ùˆ ...) | Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ Ùˆ Ú¯Ø§Ù‡ÛŒ Ø´Ø§Ø¹Ø±'


